[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED
    arduino-libraries/NTPClient
    mathieucarbou/AsyncTCP
    mathieucarbou/ESPAsyncWebServer
board_build.filesystem = littlefs
